"""changing the profile image to nullable true

Revision ID: 3a46eaae017b
Revises: 976c5b8025ef
Create Date: 2020-05-10 22:33:01.405677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a46eaae017b'
down_revision = '976c5b8025ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file', sa.String(), nullable=True))
    op.drop_column('users', 'profile_pic_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'image_file')
    # ### end Alembic commands ###
