"""updating the user table

Revision ID: 5196cfa81dbc
Revises: ac6a330cd1e4
Create Date: 2020-05-09 16:22:55.991334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5196cfa81dbc'
down_revision = 'ac6a330cd1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'blog',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blogs', 'time_in',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('blogs', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.alter_column('users', 'pass_secure',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'pass_secure',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'email')
    op.alter_column('blogs', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('blogs', 'time_in',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('blogs', 'blog',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
