"""changing the foreign key and relationship

Revision ID: 7f3cc2d21786
Revises: 75cea636038f
Create Date: 2020-05-10 01:24:25.213696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3cc2d21786'
down_revision = '75cea636038f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'blogs', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_blog_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'blog_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_blog_id_fkey', 'users', 'blogs', ['blog_id'], ['id'])
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'user_id')
    # ### end Alembic commands ###
