"""changing the profile image

Revision ID: 976c5b8025ef
Revises: a5563c6fe9f3
Create Date: 2020-05-10 22:15:08.403236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976c5b8025ef'
down_revision = 'a5563c6fe9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file', sa.String(length=20), nullable=False))
    op.drop_column('users', 'profile_pic_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'image_file')
    # ### end Alembic commands ###
